### ISSUE TITLE
This requires Ruby 2.1?

### ISSUE THREAD

**Issue by misham** [mrrooijen/msngr#1]
Can you update the minimum requirements for this gem please?

Also, is there support for subscribe notifications?

**Comment by mrrooijen** [comment]
> Can you update the minimum requirements for this gem please?

This gem is tested against the MRI 2.0, MRI 2.1, Rubinius 2.2+, and JRuby implementations.

> Also, is there support for subscribe notifications?

What are you referring to? Redis' subscribe function? Or a patternless subscribe? Or something else?
